version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      python-patch:
        patterns:
          - "*"
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /webapp
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      webapp-patch:
        patterns:
          - "*"
        update-types:
          - patch

  - package-ecosystem: docker
    directory: /docker/airflow
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /docker/sender
    schedule:
      interval: monthly
